backend:
  #based on git
  name: git-gateway
  #Branch to update (optional; defaults to master)
  #Setting it to 'main' because that's what git uses
  branch: main 


# These lines should *not* be indented
media_folder: "public/assets/blog" # Media files will be stored in the repo under static/images/uploads
public_folder: "/assets/blog" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/blog/posts'
    create: true #Allows us to create posts

    #filename template
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    #For fields:
    # label: what you'll see on the cms interface
    # name:  extracted from the front matter
    # order is important; it's the order that it shows up on the interface
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Description', name: 'description', widget: 'string'}
      - { label: 'Author', name: 'author', widget: 'string', default: 'Mario Huerta'}
      - { label: 'Date', name: 'date', widget: 'datetime'}
      - { label: 'Body', name: 'body', widget: 'markdown'}
      - { label: 'Nunjucks Template', name: 'layout', widget: 'string', default: 'baseTemplate.njk'}
      - { label: 'Website Title', name: 'websiteTitle', widget: 'hidden', default: 'yayformar.io'}
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['post']}
      #TODO: images and image captions
      #- { label: '', name: '', widget: ''}
      #- { label: '', name: '', widget: ''}
